version: '3'
services:
  receipts:
    image: 'counter-image'
    restart: always
    ports: 
      - '8080:80'
  postgres:
    image: 'postgres:alpine'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'